# This is a workflow name
name: Hello 

# runs on a trigger
on: 
  workflow_dispatch: 

# These are jobs inside the workflow
jobs:

# this is the name of the job 1
 greet:
  # this is GitHub runner
  runs-on: ubuntu-latest
  steps:
    - name: say hello to users 
      run: echo "hello users"

    - name: say hello to username
      run: echo "hello $(whoami)"

# this is the name of the job 2
 details:
    runs-on: ubuntu-latest
    steps:
      - name:  version of Python, Docker, etc
        run: docker --version && python --version
